# Application base URL
app.base-url=http://localhost:${server.port}

logging.level.root=DEBUG

# DB Config
spring.datasource.url=jdbc:mysql://localhost:3306/first_spring?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# AWS Config credentials
aws.access-key=""
aws.secret-key=""
aws.region=""
aws.bucket-name=""

# GCP Config credentials
storage.gcp.project-id=my-project-id
storage.gcp.bucket=my-bucket
storage.gcp.credentials=classpath:gcp-key.json