spring.application.name=demo
server.port=8080
# Application env
spring.profiles.active=dev

# DB Driver Config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Here it can be local|s3|azure|gcp
storage.mode=local 
storage.local.path=assets/uploads

# FCM 
fcm.notify=true'

# Expose the scheduled tasks endpoint over the web
management.endpoints.web.exposure.include=scheduledtasks
